# Generated by Django 4.0.5 on 2023-07-17 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculo', '0002_alter_vehiculo_options_alter_vehiculo_categoria_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vehiculo',
            options={'permissions': (('visualizar_catalogo', 'Puede ver Vehiculos'), ('add_vehiculomodel', 'Agregar vehiculo'))},
        ),
    ]
